parameters:
#    fundeuis_frontal.example.class: Fundeuis\FrontalBundle\Example

services:
#    fundeuis_frontal.example:
#        class: %fundeuis_frontal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
