<?php

namespace Fundeuis\InscripcionpreicfesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends EntityRepository {
    /*
     * Buscar cursos del año actual y año anterior. 
     */

    public function buscarCursosAño() {
        $year = \date('Y');
        $ayear = $year - 1;
        $aayear = $year - 2;

        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisInscripcionpreicfesBundle:Curso c WHERE c.fechainicio LIKE :fecha OR c.fechainicio LIKE :afecha OR c.fechainicio LIKE :aafecha ORDER BY c.fechainicio DESC')
                        ->setParameter('fecha', '%' . $year . '%')
                        ->setParameter('afecha', '%' . $ayear . '%')
                        ->setParameter('aafecha', '%' . $aayear . '%')
                        ->getResult();
    }

}
