<?php

namespace Fundeuis\InscripcionpreicfesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends EntityRepository {
    /*
     * Buscar cursos del año actual y año anterior. 
     */

    public function buscarCursosAno() {
        $year = \date('Y');
        $ayear = $year - 1;
        $aayear = $year - 2;

        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisInscripcionpreicfesBundle:Curso c WHERE c.fechainicio LIKE :fecha OR c.fechainicio LIKE :afecha OR c.fechainicio LIKE :aafecha ORDER BY c.fechainicio DESC')
                        ->setParameter('fecha', '%' . $year . '%')
                        ->setParameter('afecha', '%' . $ayear . '%')
                        ->setParameter('aafecha', '%' . $aayear . '%')
                        ->getResult();
    }

    /*
     * Buscar cursos por el nombre
     * Recibe el id, correspondiente al idnombrecurso, correspondiente
     * al modelo Nombrecurso.
     */

    public function buscarCursosPorNombre($id, $limite) {

        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisInscripcionpreicfesBundle:Curso c JOIN FundeuisInscripcionpreicfesBundle:Nombrecurso nc WITH c.nombrecurso = nc.idnombrecurso' .
                                ' AND c.nombrecurso = :id' .
                                'ORDER BY c.fechainicio DESC')
                        ->setParameter('id', $id)
                        ->setMaxResults($limite)//maneja el numero de resultados que se visualizaran 
                        ->getResult();
    }

    /*
     * Buscar cursos por el ano
     * Recibe el ano del curso
     */

    public function buscarCursosPorAno($ano, $limite) {

        return $this->getEntityManager()
                        ->createQuery('SELECT c FROM FundeuisInscripcionpreicfesBundle:Curso c WHERE c.fechainicio LIKE :ano' .
                                ' AND c.nombrecurso = :id' .
                                'ORDER BY c.fechainicio DESC')
                        ->setParameter('ano', '%' . $ano . '%')
                        ->setMaxResults($limite)//maneja el numero de resultados que se visualizaran 
                        ->getResult();
    }

}
