<?php

namespace Fundeuis\InscripcionpreicfesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioCursoRepository extends EntityRepository {
    /*
     * Buscar si el usuario se encuentra matriculado en uno de los cursos 
     * que no han finalizado.
     * Recibe el idusuario del modelo Usuario
     */

    public function buscarMatriculaUsuarioActiva($usuario) {
        $fecha = \date();


        return $this->getEntityManager()
                        ->createQuery('SELECT uc FROM FundeuisInscripcionpreicfesBundle:UsuarioCurso uc WHERE uc.usuario = :usuario')
                        ->setParameter('usuario', $usuario)
                        ->setParameter('fecha', new \DateTime($fecha))
                        ->getResult();
    }

}
