fundeuis_inscripcionpreicfes_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Default:index }

fundeuis_inscripcionpreicfes_cursos_crear:
    pattern: administrador/administrarCursos/crear
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Cursos:Crear }

fundeuis_inscripcionpreicfes_cursos_buscar:
    pattern: administrador/administrarCursos/{limite}.{parametro}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Cursos:Buscar, limite: 30, parametro: XXX }

#Recibe el id correspondiente al idcurso del modelo Curso.
fundeuis_inscripcionpreicfes_cursos_modificar:
    pattern: administrador/administrarCursos/modificar/{id}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Cursos:Modificar }
    
#Recibe el id correspondiente al idcurso del modelo Curso.
fundeuis_inscripcionpreicfes_cursos_vista:
    pattern: administrador/administrarCursos/vista/{id}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Cursos:Vista }

fundeuis_inscripcionpreicfes_cursos_eliminar:
    pattern: administrador/administrarCursos/eliminar
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Cursos:Eliminar }
    
#Recibe el id correspondiente al id del usuario del modelo Usuario
fundeuis_inscripcionpreicfes_cursos__matricular:
    pattern: administrador/administrarCursos/matricular/{id}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Matricula:Matricular }
    
#Recibe el id correspondiente al id de la matricula del modelo UsuarioMatricula
fundeuis_inscripcionpreicfes_cursos_matricular_cambiarestado:
    pattern: administrador/administrarCursos/matricular/cambiarEstado/{id}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Matricula:Cambiarestado }
    
#Recibe el id correspondiente al id de la matricula del modelo UsuarioMatricula
fundeuis_inscripcionpreicfes_cursos_matricular_eliminar:
    pattern: administrador/administrarCursos/matricular/eliminar/{id}
    defaults: { _controller: FundeuisInscripcionpreicfesBundle:Matricula:Eliminar }
