parameters:
#    fundeuis_user.example.class: Fundeuis\UserBundle\Example

services:
#    fundeuis_user.example:
#        class: %fundeuis_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
